import {
  SketchPicker,
  PhotoshopPicker,
  ChromePicker,
  GooglePicker,
  SliderPicker,
  SwatchesPicker,
  MaterialPicker,
  CompactPicker,
  BlockPicker,
  GithubPicker,
  TwitterPicker,
  HuePicker,
  AlphaPicker,
  CirclePicker,
} from 'react-color'

// Every picker react-color ships, with the props that make it look right
// inside a fixed-width card. `props` may be a function of the card helpers.
export const PICKERS = [
  {
    id: 'sketch',
    name: 'Sketch',
    blurb: 'Saturation square, hue + alpha sliders, editable fields, preset row.',
    Component: SketchPicker,
  },
  {
    id: 'chrome',
    name: 'Chrome',
    blurb: 'The Chrome devtools picker. Toggle between HEX, RGB and HSL fields.',
    Component: ChromePicker,
  },
  {
    id: 'photoshop',
    name: 'Photoshop',
    blurb: 'Classic two-pane dialog. Accept applies it everywhere, Cancel reverts.',
    Component: PhotoshopPicker,
    wide: true,
    props: ({ apply, revert }) => ({
      header: 'Color Picker',
      onAccept: apply,
      onCancel: revert,
    }),
  },
  {
    id: 'google',
    name: 'Google',
    blurb: 'Material-styled picker with a hue strip and numeric inputs.',
    Component: GooglePicker,
    wide: true,
    props: { header: 'Color picker' },
  },
  {
    id: 'slider',
    name: 'Slider',
    blurb: 'Lightness ramp of a single hue — handy for sequential scales.',
    Component: SliderPicker,
    full: true,
  },
  {
    id: 'swatches',
    name: 'Swatches',
    blurb: 'The full Material palette, every hue at every step.',
    Component: SwatchesPicker,
    props: { width: 320, height: 240 },
  },
  {
    id: 'material',
    name: 'Material',
    blurb: 'Minimal HEX / R / G / B inputs, no canvas.',
    Component: MaterialPicker,
    // 98px square by default, which clips the R/G/B values.
    props: { styles: { default: { material: { width: '150px', height: '110px' } } } },
  },
  {
    id: 'compact',
    name: 'Compact',
    blurb: 'A small fixed grid plus a hex field.',
    Component: CompactPicker,
  },
  {
    id: 'block',
    name: 'Block',
    blurb: 'One big swatch over its palette; the label flips for contrast.',
    Component: BlockPicker,
    props: { triangle: 'hide' },
  },
  {
    id: 'github',
    name: 'GitHub',
    blurb: 'The reaction-style strip of small swatches.',
    Component: GithubPicker,
    props: { triangle: 'hide', width: 213 },
  },
  {
    id: 'twitter',
    name: 'Twitter',
    blurb: 'Swatch grid with a hex field underneath.',
    Component: TwitterPicker,
    props: { triangle: 'hide' },
  },
  {
    id: 'circle',
    name: 'Circle',
    blurb: 'Round swatches — the cleanest fit for a small palette.',
    Component: CirclePicker,
  },
  {
    id: 'hue',
    name: 'Hue',
    blurb: 'Hue only, saturation and lightness untouched.',
    Component: HuePicker,
    full: true,
    props: { width: '100%' },
  },
  {
    id: 'alpha',
    name: 'Alpha',
    blurb: 'Opacity only — useful for overlaid distributions and CIs.',
    Component: AlphaPicker,
    full: true,
    props: { width: '100%' },
  },
]
